import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/shared/Footer";
import { NavBar } from "../components/shared/Navbar";
import { register } from "swiper/element";

register();

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
